lawyer|conservative|mod
lawyer|justice department|nn
lawyer|bush administration|in
bush administration|helped|vrel
write|bush administration|subj
write|series|obj
memos|legal|mod
series|memos|of
memos|stating|rel
stating|memo|subj
stating|that|c
were|limits|pred
power|president|gen
limits|power|on
war|wage|nn
limits|war|to
redefining|torture|obj
redefining|saying|mod
saying|that|c
convention|geneva|nn
does|not|neg
apply|convention|subj
apply|treatment|to
treatment|terrorists|of
terrorists|asserted|rel
asserted|yoo|subj
asserted|that|c
held|tightly|mod-before
held|these|subj
would|not|neg
held|convert|fc
convert|terrorists|obj
convert|memos|subj
convert|orders|to
insisted|soldiers|for
soldiers|violate|rel
violate|soldier|subj
rights|human|nn
violate|rights|obj
orders|insisted|comp1
insisted|he|subj
insisted|that|c
dictated|not|amod
dictated|white house|subj
dictated|or|punc
dictated|influenced|conj
influenced|white house|subj
influenced|content|obj
content|memos|of
believed|he|subj
believed|that|c
methods|interrogation|nn
should|not|neg
disclosed|methods|obj
disclosed|because|mod
train|then|amod
because|train|comp1
train|terrorists|subj
train|people|obj
people|resist|rel
resist|people|subj
methods|such|pre
resist|methods|obj
