helped|italy|subj
build|beijing|subj
system|solar energy|nn
build|system|obj
system|olympic games|for
olympic games|2008|in
in|and|punc
in|beyond|conj
plans|china|nn
in|plans|beyond
plans|spend|rel
spend|plan|subj
spend|$180 billion|obj
energy|renewable|mod
$180 billion|energy|on
spend|including|mod
plans|substantial|mod
plans|solar|mod
plans|heat|nn
plans|development|nn
plans|indonesia|nn
including|plans|obj
plans|build|rel
build|plan|subj
build|thousands|obj
units|small|mod
units|solar power|nn
thousands|units|of
units|boost|rel
boost|unit|subj
boost|power|obj
promotion|taiwan|gen
promotion|renewable|mod
promotion|energy|nn
capacity|yielded|rel
yielded|capacity|obj1
yielded|promotion|subj
density|world|gen
density|third|post
density|highest|mod
density|installation|nn
yielded|density|obj2
angola|solar|mod
angola|water heaters|nn
density|angola|of
developed|capacity|subj
developed|plan|obj
energy|supply|nn
developed|energy|to
population|its|gen
population|rural|mod
energy|population|to
energy|provide|rel
provide|energy|obj
provide|plan|subj
