spain|loaned|vrel
loaned|spain|obj1
loaned|philippines $4.4 million|obj2
project|solar|mod
philippines $4.4 million|project|for
project|provide|rel
provide|project|subj
300 thousand|nearly|num-mod
households|300 thousand|nn
households|rural|mod
electricity|households|to
households|schools|conj
systems|potable|mod
systems|water|nn
schools|systems|conj
systems|and|punc
portugal|health|nn
portugal|centers|nn
systems|portugal|conj
provide|planned|fc
planned|electricity|subj
planned|begin|fc
begin|electricity|subj
begin|work|obj
station|world|gen
station|biggest|mod
station|solar power|nn
work|station|on
station|2006|in
project|built|vrel
built|project|obj
built|by|by-subj
built|bp|by
create|project|subj
jobs|240|num
create|jobs|obj
counties|california|nn
counties|fresno|of
fresno|and|punc
fresno|madera|conj
operate|counties|subj
systems|500|num
systems|solar|mod
systems|electricity|nn
operate|systems|obj
systems|and|punc
powers|long island|nn
systems|powers|conj
homes|560|num
operate|homes|mod
italy|solar energy|nn
businesses|italy|by
developed|businesses|subj
train|solar power|nn
developed|train|obj
train|that|whn
powers|train|subj
conditioning|air|mod
powers|conditioning|obj
conditioning|illumination|conj
illumination|and|punc
japan|safety|nn
japan|systems|nn
illumination|japan|conj
japan|and|punc
solar panels|wales|nn
solar panels|use|nn
japan|solar panels|conj
solar panels|portion|for
power|train|nn
portion|power|of
