defines|john yoo|subj
defines|torture|obj
pain|intense|mod
pain|"|punc
torture|pain|as
pain|accompanying|rel
accompanying|pain|subj
injury|serious|mod
injury|physical|mod
accompanying|injury|obj
failure|organ|nn
accompanying|failure|such as
failure|impairment|conj
impairment|bodily function|of
bodily function|or|punc
death|even|mod
bodily function|death|conj
claims|he|subj
claims|that|c
treatment|cruel|mod
cruel|inhumane|conj
inhumane|and|punc
inhumane|degrading|conj
is|"|punc
worse|something|nn
is|worse|pred
worse|torture|than
thinks|he|subj
thinks|be|fc
aggressive|more|mod
be|aggressive|pred
aggressive|fighting|in
fighting|u.s.|subj
fighting|terrorism|obj
fighting|and|punc
fighting|find|conj
find|u.s.|subj
ways|new|mod
find|ways|obj
ways|destroy|rel
destroy|way|subj
destroy|networks|obj
destroy|even|mod
destroy|assassinating|mod
assassinating|leaders|obj
organizations|fake|mod
organizations|terrorist|mod
setting up|organizations|obj
organizations|and|punc
websites|deceptive|mod
organizations|websites|conj
setting up|and|punc
setting up|fabricating|conj
fabricating|attacks|obj
attacks|u.s.|on
thinks|he|subj
thinks|that|c
argue|judge|subj
case|his|gen
facts|case|of
push for|not|mod-before
argue|push for|fc
push for|facts|subj
theories|new|mod
push for|theories|obj
should|not|neg
make|courts|subj
make|policy|obj
issues|important|mod
issues|social|mod
policy|issues|on
