be|progress|pred
dispute|indian-pakistani|nn
progress|dispute|in
dispute|kashmir|over
ceasefire|bilateral|mod
kashmir|held|rel
held|kashmir|obj
held|ceasefire|subj
held|year|for
indian|met|rel
met|indian|obj
met|prime minister|subj
political leaders|kashmiri|nn
met|political leaders|with
time|first|amount-value
india|time|nn
political leaders|india|for
reduced|indian|subj
reduced|number|obj
troops|border|nn
number|troops|of
reduced|and|punc
reduced|announced|conj
announced|indian|subj
service|multibillion-dollar|mod
service|development plan|nn
service|bus|nn
announced|opened|fc
opened|service|obj
opened|for|mod
time|first|post
years|57|amount-value
time|years|in
president|pakistani|mod
for|suggested|comp1
suggested|president|subj
solutions|three|nn
suggested|solutions|obj
areas|kashmir|of
indian-pakistani|independent|mod
independent|or|punc
independent|placed|conj
placed|joint|under
control|indian-pakistani|subj
control|under|guest
control|un|under
control|administration|obj
administration|ruled|rel
ruled|administration|obj
ruled|india|subj
ruled|division|out
lines|religious|mod
division|lines|along
borders|international|mod
redrawing|borders|obj
