mother|and|punc
mother|spouse|conj
judge|federal|mod
spouse|judge|of
judge|handling|rel
handling|judge|subj
handling|lawsuit|obj
supremacists|white|mod
lawsuit|supremacists|against
enforcement|murdered|mod
enforcement|law|nn
were|enforcement|pred
investigated|officials|subj
investigated|connection|obj
connection|matthew hale|to
supremacist|white|mod
supremacists|white|mod
clashed|supremacists|subj
clashed|crowd|with
crowd|boston|in
boston|where|wha
survivors|holocaust|nn
celebrated|survivors|subj
celebrated|liberation|obj
camps|nazi|mod
camps|concentration|nn
liberation|camps|of
group|texas|nn
aryan wear|group|appo
offers|aryan wear|subj
offers|clothing|obj1
supremacists|white|mod
clothing|supremacists|for
candidate|charlotte nc|nn
candidate|city council|nn
supremacists|dropped out|rel
dropped out|supremacists|obj
dropped out|candidate|subj
dropped out|race|of
dropped out|when|wha
disclosed|it|obj
offers|he|obj2
supremacist|white|mod
erupted|supremacist|to
erupted|website violence|subj
erupted|toledo oh|in
erupted|when|wha
supremacists|white|mod
assembled|supremacists|subj
assembled|march|for
violence|black|mod
violence|gang|nn
march|violence|against
violence|whites|against
