u.s.|e.u|conj
e.u|and|punc
e.u|norway|conj
recalled|u.s.|subj
ambassadors|their|gen
recalled|ambassadors|obj
ambassadors|protest|rel
protest|ambassador|subj
seizure|king|gen
protest|seizure|obj
seizure|power|of
power|march 7th|on
announced|urging|mod-before
urging|japan|subj
urging|return|obj
return|democracy|to
announced|japan|subj
announced|7.1 million dollars|obj
7.1 million dollars|aid|of
aid|nepal|to
frozen|march 10th|as of
frozen|world bank|subj
frozen|release|obj
aid|more|mod
release|aid|of
aid|nepal|to
india|and|punc
india|britain|conj
suspended|india|subj
aid|their|gen
aid|military|mod
suspended|aid|obj
u.s.|and|punc
u.s.|norway|conj
considering|u.s.|subj
experts|similar|mod
experts|action|nn
experts|nine|nn
experts|u.n.|nn
experts|human rights|nn
considering|expressed|fc
expressed|experts|subj
concern|deep|mod
expressed|concern|obj
actions|king|gen
concern|actions|over
international federation|journalists|of
asserted|international federation|subj
asserted|that|c
media|nepal|gen
suffocated|"|punc
suffocated|media|obj
