22|at least|num-mod
blacks|22|nn
died|blacks|subj
de|wilmington|nn
died|de|in
died|when|wha
supremacists|white|mod
rioted|supremacists|subj
rioted|1898|in
rioted|and|punc
rioted|attempted|conj
attempted|supremacists|subj
attempted|put|fc
put|supremacist|subj
put|members|obj
members|office|in
authorities|force|nn
office|authorities|by
authorities|investigated|vrel
investigated|authorities|obj
investigated|whether|c
leader|former|mod
leader|ku klux klan|nn
david duke|leader|appo
violated|david duke|subj
laws|racism|nn
violated|laws|obj
laws|speech|in
speech|sweden|in
agitating|ethic|against
group|group a|nn
group|neo-nazi|nn
staged|group|subj
staged|rally|obj
rally|toledo oh hundred|in
toledo oh hundred|officers|of
officers|stood|vrel
stood|officers|obj1
stood|guard|obj2
30|more than|num-mod
people|30|nn
injured|people|obj
arrested|16|obj
violence|racial|mod
arrested|violence|in
violence|sydney australia|in
sydney australia|december 2005|in
december 2005|began|rel
began|december 2005|obj
began|violence|subj
began|when|wha
youths|drunken|mod
youths|white|mod
mobs|youths|of
attacked|mobs|subj
attacked|people|obj
people|who|whn
looked|people|subj
