faced|aftermath|in
aftermath|storm|of
storm|that|whn
slammed|storm|subj
slammed|southern california|obj
southern california|six|for
faced|residents|subj
gridlock|traffic|nn
faced|gridlock|obj
gridlock|and|punc
amounts|massive|mod
gridlock|amounts|conj
amounts|mud|of
mud|rubble|conj
rubble|and|punc
rubble|debris|conj
debris|hurried|rel
hurried|debris|obj
hurried|transportation department|subj
hurried|clear|mod
clear|transportation department|subj
department|major|mod
department|roads|nn
department|fire|nn
clear|department|obj
department|and|punc
employees|california highway patrol|nn
department|employees|conj
employees|worked|vrel
worked|employees|obj
worked|clock|round
was|critical|pred
was|reopen|mod
reopen|it|subj
reopen|roads|obj
roads|and|punc
roads|highways|conj
reopen|so|mod
get back|people|subj
caltrans|work|nn
get back|caltrans|to
so|estimated|comp1
estimated|fin|subj
estimated|spent|fc
spent|it|subj
spent|$11 million|obj
repairs|immediate|mod
$11 million|repairs|for
spent|and|punc
spent|spend|conj
spend|it|subj
spend|$40 million|obj
$40 million|roads|on
roads|and|punc
officials|other|mod
officials|public|mod
officials|repairs|nn
officials|state|nn
roads|officials|conj
officials|and|punc
officials|farm|conj
farm|and|punc
damage|insurance|nn
damage|groups|nn
damage|estimated|mod
farm|damage|conj
damage|homes|to
homes|roads|conj
roads|and|punc
roads|farms|conj
farms|over $100 million|at
