authorities|swedish|nn
investigating|authorities|subj
leader|former|mod
leader|kkk|nn
investigating|leader|obj
leader|and|punc
politician|us|nn
leader|politician|conj
violations|racial|mod
violations|law|nn
politician|violations|for
investigating|after|mod
after|delivered|comp1
delivered|he|subj
delivered|speech|obj
speech|neo-nazi|to
neo-nazi|gathering|rel
gathering|neo-nazi|subj
supremacists|white|mod
gathering|suspected|fc
suspected|supremacists|obj
suspected|killing|in
activist|jewish defense league|nn
killing|activist|of
prison|federal|mod
activist|prison|in
staged|neo-nazis|subj
hall|city|nn
avoid|hall|at
hall|toledo|in
avoid|violence|obj
700|about|num-mod
police|700|nn
deployed|police|obj
leaders|community|mod
promised|leaders|subj
promised|be|fc
be|peaceful|pred
activities|rally-related|mod
confined|activities|obj
in|hall|nn
in|grounds|nn
confined|in|to
sydney|thousands|appo
youths|white|mod
thousands|youths|of
confined|including|mod
including|sydney|subj
supremacists|white|mod
including|supremacists|obj
supremacists|and|punc
supremacists|neo-nazis|conj
beachgoers|attacked|mod
beachgoers|middle|mod
beachgoers|eastern-looking|mod
police|2,000|num
deployed|police|obj
deployed|maintain|mod
maintain|police|subj
maintain|order|obj
