fell|storms|by
storms|beginning|rel
beginning|storm|subj
december 2004|late|mod
beginning|december 2004|in
drenching|heaviest|mod
40|nearly|num-mod
years|40|amount-value
inches|years|nn
15|over|num-mod
inches|15|amount-value
drenching|inches|in
fell|drenching|subj
days|first nine|amount-value
fell|days|during
days|january|of
resulted|storm|subj
deaths|human|nn
resulted|deaths|in
deaths|and|punc
deaths|injuries|conj
injuries|created|rel
created|injuries|obj
created|it|subj
mudslides|and|punc
mudslides|rockslides|conj
rockslides|which|whn
caused|rockslides|subj
outages|power|mod
caused|outages|obj
outages|evacuations|conj
evacuations|and|punc
evacuations|disruption|conj
beaches|rail|nn
beaches|services|nn
disruption|beaches|of
parks|state|nn
parks|and|punc
parks|mountain|conj
mountain|and|punc
resorts|ski|nn
mountain|resorts|conj
closed|parks|obj
said|national weather service|subj
said|occurs|fc
occurs|system|subj
occurs|only|guest
years|5-10|amount-value
occurs|years|obj
weather|extraordinary|mod
attributed|weather|obj
attributed|confluence|to
air|tropical|mod
confluence|air|of
air|south pacific|from
south pacific|and|punc
front|cold|nn
south pacific|front|conj
front|north|from
