condemned|including|mod-before
including|country|subj
including|u.s.|obj
u.s.|britain|conj
britain|india|conj
india|and|punc
india|japan|conj
condemned|countries|subj
seizure|nepali king gyanendra|gen
condemned|seizure|obj
seizure|power|of
yet|not|mod
decided|yet|amod
power|decided|rel
decided|power|obj
decided|u.s.|subj
decided|whether|c
continue|u.s.|subj
military|its|gen
continue|military|obj
military|and|punc
military|development|conj
india|aid|nn
yet|not|mod
commented on|yet|amod
commented on|india|subj
aid|its|gen
aid|military|mod
commented on|aid|obj
commented on|but|punc
commented on|expected|conj
continue|india|subj
continue|support|mod
support|u.s.|subj
fight|nepal|gen
support|fight|obj
rebels|maoist|nn
fight|rebels|against
e.u|and|punc
e.u|u.n.|conj
condemned|e.u|subj
condemned|move|obj
condemned|and|punc
condemned|called|conj
called|e.u|obj
return|immediate|mod
organizations|multi-party|mod
organizations|democracy|nn
return|organizations|to
organizations|including|rel
including|international organization|subj
including|amnesty international|obj
called|denounced|mod
denounced|return|subj
denounced|suspension|obj
suspension|civil liberties|of
remained|alone|mod-before
remained|china|subj
remained|neutral|desc
remained|maintaining|mod
maintaining|china|subj
maintaining|that|c
matter|"|punc
matter|internal|mod
was|matter|pred
