say|advocates|subj
farm|nantucket|nn
farm|wind|nn
say|produce|fc
produce|farm|subj
fourths|three|nn
produce|fourths|obj
needs|electricity|nn
fourths|needs|of
produce|for|mod
farms|cape cod|nn
farms|area|nn
farms|wind|nn
for|reduce|comp1
reduce|farms|subj
reduce|reliance|obj
reliance|fossil fuel|on
pollution|bring|rel
bring|pollution|obj1
bring|it|subj
bring|jobs|obj2
opponents|attraction|nn
argue|opponents|subj
argue|that|c
place|wrong|mod
is|place|pred
place|farm|for
relies on|plan|subj
technology|unproved|mod
relies on|technology|obj
project|large|mod
project|wind|nn
project|turbine|nn
planned|project|obj
planned|taiwan|in
farm|proposed|mod
farm|wind|nn
farm|overlooking|rel
overlooking|farm|subj
site|ireland|gen
site|oldest|mod
site|religious|mod
overlooking|site|obj
ruled out|farm|obj
ruled out|fear|for
fear|disrupt|comp1
disrupt|it|subj
tranquility|sanctuary|gen
disrupt|tranquility|obj
