rains|-breaking|mod
brought|rains|subj
brought|danger|obj
danger|and|punc
danger|destruction|conj
california|southern|mod
destruction|california|to
weeks|first|post
california|weeks|in
weeks|2005|of
storms|early|mod
storms|january|nn
2005|dropped|rel
dropped|2005|obj1
dropped|storms|subj
rain|more|mod
dropped|rain|obj2
rain|los angeles|in
dropped|than|mod
residents|its|gen
residents|average|mod
residents|annual|mod
residents|amount|nn
residents|thousand|nn
than|endured|comp1
endured|residents|subj
outages|power|mod
endured|outages|obj
necessitated|conditions|subj
landslides|widespread|mod
landslides|evacuations|nn
necessitated|landslides|obj
landslides|mudslides|conj
mudslides|floods|conj
floods|and|punc
trees|downed|mod
floods|trees|conj
trees|caused|vrel
caused|trees|obj1
destruction|massive|mod
caused|destruction|obj2
destruction|homes|of
motorists|roads|nn
motorists|stranded|mod
required|motorists|subj
schools|overtaxed|mod
schools|emergency|mod
schools|workers|nn
rescue|schools|by
schools|businesses|conj
lines|rail|nn
businesses|lines|conj
lines|and|punc
lines|roads|conj
required|closed|fc
closed|rescue|obj
closed|beaches|obj
leaks|sewage|nn
closed|leaks|for
accidents|traffic|nn
number|accidents|of
leaks|tripled|rel
tripled|leaks|obj
tripled|number|subj
in|previous|mod
in|dry|mod
in|weekend|nn
tripled|in|from
in|caused|rel
caused|in|obj1
caused|storms|subj
20|at least|num-mod
deaths|20|nn
caused|deaths|obj2
deaths|and|punc
deaths|dozens|conj
dozens|injuries|of
