rocked|explosions|subj
resorts|three|nn
resorts|egyptian red sea|nn
rocked|resorts|obj
resorts|popular|pnmod
popular|israelis|with
explosion|largest|mod
israelis|occurred|rel
occurred|israelis|obj
occurred|explosion|subj
occurred|taba hilton|in
occurred|just|mod
border|israeli|mod
just|border|across
border|and|punc
two|other|num-mod
border|two|conj
villages|nearby|mod
two|villages|in
followed|explosions|subj
followed|warnings|obj
intelligence|israeli|nn
warnings|intelligence|from
intelligence|keep|rel
keep|intelligence|subj
keep|sinai desert|out of
is|not|neg
how many|clear|mod
killed|how many|obj
killed|blasts|in
numbers|conflicting|mod
numbers|casualty|nn
reported|numbers|obj
reports|official|mod
were|reports|pred
reports|cause|about
cause|blasts|of
but|believe|comp1
believe|police|subj
believe|caused|fc
caused|they|obj
caused|by|by-subj
bombs|car|nn
caused|bombs|by
claimed|world islamic group|subj
explosion|taba|nn
responsibility|explosion|for
explosion|but|punc
explosion|it|conj
claimed|verified|fc
verified|responsibility|obj
