helped|betty friedan|subj
helped|empower|mod
empower|betty friedan|subj
empower|women|obj
women|fight for|rel
fight for|woman|subj
fight for|parity|obj
parity|men|with
men|workplace|in
jobs|equal|mod
workplace|jobs|conj
jobs|pay|conj
pay|and|punc
pay|respect|conj
encouraged|she|subj
encouraged|them|obj
encouraged|reject|mod
reject|she|subj
role|"|punc
role|contented|mod
role|homemaker|nn
role|"|punc
reject|role|obj
participation|demand|nn
participation|fuller|mod
some|life|nn
participation|some|in
considered|participation|subj
woman|her|gen
influential|most|mod
woman|influential|mod
considered|woman|obj1
millennium|second|post
woman|millennium|of
millennium|raised|rel
raised|woman|obj
raised|she|subj
considered|issues|obj2
leave|paid|mod
leave|maternity|nn
issues|leave|such as
childcare|affordable|mod
leave|childcare|conj
training|job|nn
childcare|training|conj
training|women|for
women|and|punc
determination|reproductive|mod
determination|self|nn
women|determination|conj
determination|which|whn
were|radical|pred
radical|1960 's|in
were|but|punc
were|are|conj
important|still|mod
are|important|pred
important|today|guest
felt|feminists|subj
felt|focused|fc
focused|she|subj
focused|too|guest
focused|much|obj
much|concerns|on
married women|white|mod
married women|middle class|nn
concerns|married women|of
women|all|pre
married women|women|instead of
