heard|supreme court|subj
heard|arguments|obj
cases|two|nn
arguments|cases|in
cases|march 2nd|on
cases|conditions|about
display|government|subj
display|ten commandments|obj
displays|such|pre
violated|displays|subj
amendment|first|post
violated|amendment|obj
case|texas|nn
concerns|case|subj
monument|40-year-old|mod
monument|granite|nn
concerns|monument|obj
monument|ten commandments|of
monuments|17|num
one|monuments|of
monuments|grounds|on
capital|state|nn
grounds|capital|of
case|kansas|nn
capital|concerns|rel
concerns|grounds|obj
concerns|case|subj
framed|one|subj
framed|copies|obj
copies|ten commandments|of
ten commandments|which|whn
hang|ten commandments|subj
documents|non-religious|nn
hang|documents|with
courthouses|two|nn
courthouses|county|nn
documents|courthouses|in
modified|displays|obj
modified|twice|mod
twice|response|in
rulings|lower court|nn
expected|rulings|to
'connor|justice|nn
justice|o|person
response|expected|comp1
cast|'connor|subj
votes|swing|nn
cast|votes|obj
