efforts|revive|comp1
revive|talks|obj
government|sri lankan|nn
talks|government|between
government|and|punc
rebels|tamil tiger|nn
government|rebels|conj
stalled|efforts|obj
stalled|by|by-subj
clashes|persistent|mod
stalled|clashes|by
groups|rival|mod
groups|rebel|mod
clashes|groups|between
between|and|punc
between|by|conj
in|continued|mod
in|killings|nn
between|in|by
october|early|mod
group|top|mod
group|rebel|mod
was|in|pred
was|switzerland|in
switzerland|prepare for|rel
prepare for|switzerland|subj
round|next|post
prepare for|round|obj
round|talks|of
prepare for|while|mod
while|said|comp1
said|government|subj
said|that|c
finalized|it|subj
finalized|set|obj
proposals|counter|nn
set|proposals|of
proposals|resumption|for
negotiations|direct|mod
resumption|negotiations|of
envoy|japan|gen
envoy|special|mod
arrived|envoy|subj
arrived|sri lanka|in
sri lanka|27 october|on
arrived|for|mod
visit|7-day|nn
visit|encourage|rel
encourage|visit|subj
resumption|early|mod
encourage|resumption|obj
japan|peace|nn
japan|talks|nn
resumption|japan|of
for|is|comp1
is|optimistic|pred
is|and|punc
is|promised|conj
promised|visit|subj
assistance|continued|mod
promised|assistance|obj1
assistance|country|for
promised|reconstruction|obj2
