told|times|according to
advisors|senior|mod
told|advisors|subj
told|prince|obj
prince|charles|person
told|that|c
marry|either|amod
marry|he|subj
marry|parker bowles|obj
marry|or|punc
marry|banish|conj
banish|he|subj
banish|her|obj
life|his|gen
banish|life|from
life|avoid|rel
avoid|life|subj
crisis|constitutional|mod
avoid|crisis|obj
become|he|subj
become|king|obj
become|if|c
became|he|subj
became|king|obj
have|she|subj
have|title|obj
title|princess consort|of
title|vague|mod
title|that|whn
let|title|subj
develop|her|subj
role|her|gen
develop|role|obj
role|time|over
role|australia|in
group|that|whn
wants|group|subj
wants|sever|fc
sever|ties|obj
monarchy|british|mod
ties|monarchy|with
reported|group|subj
reported|surge|obj
members|new|mod
surge|members|of
members|reaction|in
reaction|news|to
news|announced|comp1
announced|prime minister|subj
announced|that|c
would|not|neg
cause|marriage|subj
cause|australia|obj
australia|abandon|rel
abandon|australia|subj
monarch|british|mod
abandon|monarch|obj
monarch|head of state|as
