prince|charles|person
announced|prince|subj
announced|unexpectedly|guest
announced|that|c
marry|he|subj
marry|camilla parker bowles|obj
camilla parker bowles|april|in
castle|windsor|nn
camilla parker bowles|castle|at
minister|british prime|nn
minister|archbishop|conj
archbishop|canterbury|of
elizabeth|queen|nn
canterbury|elizabeth|conj
elizabeth|and|punc
sons|prince|gen
prince|charles|person
elizabeth|sons|conj
were|pleased|pred
reacted|engagement|over
pleased|reacted|comp1
reacted|brits|subj
reacted|more|mod
more|relief|with
relief|happiness|than
reacted|viewing|mod
viewing|brit|subj
viewing|it|obj
conclusion|logical|mod
viewing|conclusion|as
situation|difficult|mod
receive|situation|to
conclusion|receive|comp1
receive|camilla|subj
hrh|title|nn
receive|hrh|obj
duchess|cornwall|of
ascends|charles|subj
ascends|thrown|to
become|she|subj
become|hrh|obj
consort|princess|subj
wedding|civil service|appo
civil service|family|for
family|and|punc
family|friends|conj
followed|wedding|obj
followed|by|by-subj
followed|prayer|by
couple|dedication|nn
couple|service|nn
honeymoon|couple|subj
honeymoon|scotland|in
