measures|heavy|mod
measures|security|nn
targeted|measures|despite
scores|attacks|of
targeted|scores|subj
polling places|iraqi|mod
targeted|polling places|obj
polling places|country|throughout
country|days|in
days|preceding|rel
preceding|day|subj
preceding|sunday|guest
elections|january 30|nn
elections|iraqi|mod
preceding|elections|obj
casualties|40|num
casualties|polling stations|nn
casualties|destroyed|mod
preceding|casualties|with
were|including|mod-before
policemen|iraqi|mod
including|policemen|obj
policemen|soldiers|conj
soldiers|child|conj
child|and|punc
child|woman|conj
were|low|pred
were|because|mod
most|buildings|of
were|not|neg
because|occupied|comp1
occupied|most|obj
polling places|attacks|nn
polling places|struck|mod
polling places|baghdad|in
tikrit|samarra|conj
samarra|basra|conj
basra|kirkuk , al-dur|conj
kirkuk , al-dur|baiji|conj
baiji|shorgat|conj
shorgat|and|punc
shorgat|moqdadiya violence|conj
escalate|tikrit|subj
escalate|sunday|on
escalate|and|punc
escalate|continue|conj
continue|tikrit|subj
continue|after|mod
sunnis|elections|nn
after|expected|comp1
boycott|sunnis|subj
boycott|elections|obj
turnout|high|mod
expected|turnout|obj
expected|shiites|among
shiites|and|punc
shiites|kurds|conj
