bobby fischer|chess|nn
bobby fischer|legend|nn
held|bobby fischer|obj
held|detention|in
detention|japan|in
months|eight|amount-value
japan|months|for
held|after|mod
trying|bobby fischer|subj
trying|leave|fc
leave|tokyo|obj
passport|revoked|mod
passport|us|nn
tokyo|passport|on
after|faces|comp1
faces|he|subj
faces|deportation|obj
deportation|and|punc
deportation|prison|conj
prison|us|in
us|violating|for
violating|he|subj
violating|sanctions|obj
yugoslavia|former|mod
sanctions|yugoslavia|on
yugoslavia|playing|by
playing|there|mod
supporters|1992|num
playing|supporters|in
supporters|worked|vrel
worked|supporters|obj
worked|secure|mod
passage|his|gen
secure|passage|obj
passage|iceland|to
revered|he|obj
hero|national|mod
revered|hero|as
hero|beating|for
beating|he|subj
beating|boris spassky|obj
beating|there|mod
iceland|1972|num
parliament|iceland|gen
beating|parliament|in
parliament|granted|vrel
granted|parliament|obj1
granted|fischer|obj2
passport|foreigner|gen
passport|and|punc
passport|residency|conj
fischer|permit|rel
permit|fischer|obj
permit|passport|subj
permit|but|mod
but|was|comp1
was|not|neg
was|that|c
citizenship|icelandic|nn
enable|citizenship|subj
enable|japan|obj
japan|free|rel
free|japan|subj
free|fischer|obj
was|enough|guest
enough|receiving|after
receiving|that|subj
receiving|assurance|obj
granted|parliament|subj
granted|it|obj
granted|him|to
