engagement|news of prince charles|gen
news of prince charles|and|punc
news of prince charles|camilla parker bowles|conj
dominated|engagement|subj
dominated|airways|obj
accepted|generally|mod-before
accepted|people|subj
accepted|marriage|obj
marriage|but|punc
reservations|had|mod
reservations|strong|mod
marriage|reservations|conj
reservations|camilla|about
camilla|becoming|rel
becoming|camilla|subj
becoming|"|punc
prince charles|queen camilla|nn
prince charles|"|punc
becoming|prince charles|obj
advisors|senior|mod
said|advisors|subj
said|choose|fc
choose|he|subj
marrying|he|subj
camilla|his|gen
camilla|long-term|mod
camilla|partner|nn
marrying|camilla|obj
camilla|agreed|pnmod
agreed|marriage|to
marrying|but|mod
present|brits|obj
lifestyle|conventional|mod
brits|lifestyle|with
lifestyle|required|vrel
required|lifestyle|obj
required|before|mod
before|become|comp1
become|he|subj
become|king chinese|obj
but|predicted|comp1
predicted|soothsayers|subj
marriage|long|mod
long|and|punc
long|happy|conj
predicted|marriage|obj
marriage|prince|for
prince|charles|person
prince|and|punc
prince|camilla they|conj
camilla they|determined|pnmod
determined|that|c
date|wedding|nn
be|auspicious|pred
camilla they|based|vrel
based|camilla they|obj
sign|charles|gen
sign|chinese|nn
sign|zodiac|nn
based|sign|on
