announced|february 10th|on
prince|charles|person
announced|prince|subj
announced|that|c
marry|he|subj
marry|his|obj
camilla parker bowles that|long-time|nn
camilla parker bowles that|love|nn
camilla parker bowles that|evening|rel
evening|camilla parker bowles that|subj
evening|couple|obj
attended|camilla parker bowles that|subj
dinner|gala|mod
attended|dinner|obj
dinner|windsor castle|at
windsor castle|support|rel
support|windsor castle|subj
support|one|obj
charities|prince|gen
one|charities|of
ceremony|private|mod
ceremony|civil|mod
be|ceremony|pred
ceremony|windsor castle|at
windsor castle|friday|on
archbishop|canterbury|of
preside|archbishop|subj
religious service|subsequent|mod
preside|religious service|over
religious service|st. george|in
receive|chapel parker bowles|subj
receive|title|obj
highness|her|gen
highness|royal|mod
title|highness|of
duchess|cornwall queen elizabeth|of
cornwall queen elizabeth|prince|conj
prince|edward|person
prince|and|punc
prince|prince|conj
prince|harry|person
prince|and|punc
tony blair|prime minister|title
all|tony blair|nn
prince|all|conj
highness|gave|rel
gave|highness|obj1
gave|duchess|subj
approval|their|gen
gave|approval|obj2
