son|her|gen
killed|son|obj
launched|iraq cindy sheehan|subj
campaign|anti-war|mod
launched|campaign|obj
campaign|made|rel
made|campaign|obj1
made|she|subj
appearances|public|mod
made|appearances|desc
appearances|oppose|rel
oppose|appearance|subj
oppose|war|obj
oppose|and|punc
oppose|founded|conj
founded|appearance|subj
group|anti-war|mod
founded|group|obj
gold star families|peace|for
peace|received|rel
received|peace|obj
received|she|subj
support|gold star families|subj
groups|anti-war|mod
traveled to|groups|from
groups|washington|in
washington|and|punc
washington|spoke|conj
spoke|democratic|with
congressmen|she|person
support|traveled to|fc
traveled to|congressmen|subj
traveled to|texas|obj
activists|anti-war|mod
texas|activists|with
activists|seek|rel
seek|activist|subj
seek|meeting|obj
meeting|president|with
president|bush|person
ranch|his|gen
president|ranch|at
denied|she|obj1
denied|meeting|obj2
denied|and|punc
denied|camped|conj
camped|she|subj
ranch|bush|nn
camped|ranch|near
camped|saying|mod
saying|she|subj
saying|remain|fc
remain|she|subj
remain|there|mod
remain|until|mod
bush|met|vrel
met|bush|obj
activists|her|gen
activists|leading|mod
activists|anti-war|mod
met|activists|with
until|joined|comp1
joined|bush|subj
protest|her|gen
joined|protest|obj
protest|texas|in
received|she|subj
received|liberal|obj
liberal|support|rel
support|liberal|obj
support|internet|subj
