israelis|explosion|nn
fled|immediately|mod-before
after|fled|comp1
fled|israelis|subj
fled|border|across
border|facilitated|rel
facilitated|border|obj
facilitated|egyptians|subj
authorities|evacuation|nn
authorities|egyptian|mod
cooperated|authorities|subj
fire|israeli|mod
cooperated|fire|with
fire|and|punc
personnel|rescue|nn
fire|personnel|conj
cooperated|allowing|mod
allowing|authority|subj
cross|ambulances|subj
cross|border|obj
border|evacuate|rel
evacuate|border|subj
evacuate|wounded|obj
wounded|and|punc
wounded|search|conj
search|those|for
those|trapped|pnmod
groups|debris|nn
groups|two|nn
trapped|groups|in
groups|one|conj
one|calling|rel
calling|one|subj
calling|itself|obj1
calling|islamic unity brigade|desc
islamic unity brigade|and|punc
unknown|previously|mod
pro|unknown|mod
islamic unity brigade|pro|conj
group|al qaeda islamic|nn
called|group|subj
called|islamic tawhid brigades|obj
called|claimed|mod
claimed|responsibility|subj
responsibility|bombings|for
bombings|offered|rel
offered|bombings|obj1
offered|group|subj
offered|details|obj2
carried out|it|subj
carried out|attack|obj
claims|their|gen
could|not|neg
verified|claims|obj
minister|israel|gen
minister|deputy|nn
minister|defense|nn
believed|minister|subj
network|al qaeda|nn
network|terrorist|mod
believed|involved|fc
involved|network|obj
