people|six|nn
died|people|subj
elections|sunday|nn
elections|january 30|nn
elections|iraqi|mod
died|elections|in
iraqi|heavy|mod
security|iraqi|mod
defied|security|despite
security|polling places|around
defied|iraqis|subj
threats|insurgents|gen
defied|threats|obj
threats|attacks|of
attacks|order|in
order|vote|comp1
vote|iraqi|subj
was|little|pred
turn-out|fallujah|in
fallujah|and|punc
fallujah|samarra|conj
attacks|security|nn
attacks|situation|nn
serious|most|mod
attacks|serious|mod
samarra|attacks|because of
were|in|pred
were|baghdad|in
baghdad|where|wha
people|five|nn
people|including|rel
including|people|subj
including|policeman|obj
killed|people|obj
bomber|suicide|nn
killed|bomber|along with
along with|and|punc
along with|in|conj
along with|balad|in
killed|woman|obj
were|also|guest
were|attacks|pred
attacks|basra|in
basra|and|punc
basra|mosul|conj
reported|casualties|obj
