1963|betty friedan|gen
the feminine mystique|classic|mod
the feminine mystique|"|punc
started|"|punc
started|the feminine mystique|subj
revolution|social|mod
started|revolution|obj
revolution|that|whn
led to|revolution|subj
women|modern|mod
movement|women|gen
led to|movement|obj
included|it|obj
magazine|human events|nn
list|magazine|gen
included|list|in
ten|"|punc
list|ten|of
frieden|19th|mod
19th|and|punc
19th|20th|conj
frieden|centuries|nn
frieden|"|punc
harmful books|frieden|of
ten|helped|rel
helped|harmful books|subj
found|ten|subj
organization|national|nn
found|organization|obj
organization|women|for
women|1966|in
was|one|pred
one|founders|of
in|national women|gen
in|political|mod
in|caucus|nn
founders|in|of
in|1970|num
led|she|subj
women|500,000-person|mod
strike|women|gen
strike|equality|for
equality|fifth avenue friedan|down
pushed for|strike|subj
pay|equal|mod
pushed for|pay|obj
ads|sex-neutral|mod
ads|help-wanted|mod
pay|ads|conj
leave|maternity|nn
ads|leave|conj
centers|child-care|nn
leave|centers|conj
parents|working|mod
centers|parents|for
parents|and|punc
topics|other|mod
parents|topics|conj
topics|considered|vrel
considered|topics|obj1
considered|radical|obj2
ads|time|at
