days|six|amount-value
days|cindy sheehan|after
arrived|days|subj
protestors|texas|nn
350|more than|num-mod
protestors|350|nn
arrived|protestors|in
arrived|including|mod
including|days|subj
including|members|obj
members|code pink|of
code pink|and|punc
code pink|true majority|conj
true majority|and|punc
100|over|num-mod
people|100|nn
true majority|people|conj
people|supporting|rel
supporting|people|subj
president|bush|person
supporting|converged|fc
converged|president|subj
converged|camp casey|on
sheehan|sheehan|gen
sheehan|texas|nn
sheehan|encampment|nn
continued|sheehan|subj
protests|her|gen
continued|protests|obj
support|received|mod
groups|liberal|mod
support|groups|from
groups|announced|rel
announced|groups|obj
announced|she|subj
plans|support|subj
plans|for|guest
plans|1000|for
protest|candlelight|nn
plans|protest|obj
sheehan|vigils|nn
sheehan|nationwide|mod
protest|stated|rel
stated|protest|obj
stated|sheehan|subj
continue|she|subj
activities|her|gen
activities|anti-war|mod
continue|activities|obj
activities|duration|for
vacation|bush|gen
duration|vacation|of
unless|met with|comp1
met with|he|subj
met with|her|obj
was|savvy|pred
savvy|using|in
using|sheehan|subj
using|media|obj
cause|her|gen
media|cause|for
cause|sought|rel
sought|cause|obj
sought|she|subj
sought|embarrass|mod
embarrass|she|subj
embarrass|president|obj
president|strategy|as
strategy|advance|rel
advance|strategy|subj
advance|her|obj1
objective|political|mod
advance|objective|obj2
