upgraded|hurricane rita|obj
upgraded|category 3|to
upgraded|after|mod
slamming|hurricane rita|subj
slamming|cuba|obj
cuba|and|punc
keys|florida|nn
cuba|keys|conj
keys|packed|rel
packed|keys|obj
packed|she|subj
rita|115|num
rita|mph|nn
wind|rita|of
after|upgraded|comp1
upgraded|wind|obj
dangerous|extremely|mod
hurricane|dangerous|mod
hurricane|category 4|nn
upgraded|hurricane|to
upgraded|as|mod
as|bore down on|comp1
bore down on|it|subj
in|texas|nn
bore down on|in|obj
rita|gulf of mexico|nn
in|gained|rel
gained|in|obj1
gained|rita|subj
gained|strength|obj2
hurricane|category 5|nn
strength|hurricane|to
people|one million|nn
evacuated|people|subj
evacuated|gulf coast cuba|obj
gulf coast cuba|set|vrel
set|gulf coast cuba|obj1
set|up|guest
shelters|600|num
set|shelters|obj2
shelters|havana|in
havana|housing|rel
housing|havana|subj
staff|230000|num
staff|evacuees|nn
staff|companies|nn
staff|evacuated|mod
housing|staff|obj
staff|gulf|from
rita|hurricane|nn
gulf|rita|as
rita|approached|vrel
approached|rita|obj
approached|shutting|mod
shutting|down|guest
70|over|num-mod
shutting|70|obj
production|us|nn
production|oil|nn
production|area|in
