singer/songwriter|successful|mod
cat stevens|singer/songwriter|appo
decades|two|amount-value
singer/songwriter|decades|for
abandoned|cat stevens|subj
career|his|gen
career|music|nn
abandoned|career|obj
career|converted|vrel
converted|career|obj
converted|islam|to
converted|and|punc
converted|changed|conj
changed|career|subj
name|his|gen
changed|name|obj
name|yusuf islam|to
changed|30 years ago|mod
30 years ago|devoted|rel
devoted|30 years ago|obj1
devoted|he|subj
devoted|himself|obj2
devoted|charity|to
charity|and|punc
campaigns|peace|nn
charity|campaigns|conj
to|and|punc
to|to|conj
schools|single-faith|mod
schools|islamic|mod
to|schools|to
schools|britain|in
devoted|but|punc
devoted|denies|conj
denies|30 years ago|obj
denies|he|subj
denies|supporting|mod
supporting|he|subj
activities|terrorist|mod
supporting|activities|obj
activities|september 2004|in
barred|islam|obj
entering|islam|subj
entering|united states|obj
entering|because|mod
name|his|gen
because|appeared|comp1
appeared|name|subj
no-fly|"|punc
appeared|no-fly|on
list|people|of
deemed|list|subj
risks|security|nn
vowed|risks|as
deemed|vowed|fc
vowed|he|subj
vowed|find|fc
find|he|subj
find|out|guest
barred|he|obj
find|received|fc
received|islam|subj
received|man|obj
prize|peace|nn
man|prize|of
work|his|gen
prize|work|for
work|promoting|rel
promoting|work|subj
promoting|peace|obj
promoting|reconciling|conj
reconciling|work|subj
reconciling|people|obj
reconciling|and|punc
reconciling|condemning|conj
condemning|work|subj
condemning|terrorism|obj
