rushed|january 31 , 2005|on
trial|michael jackson|gen
trial|molestation|nn
january 31 , 2005|began|rel
began|january 31 , 2005|obj
began|trial|subj
selection|jury|nn
began|selection|with
selection|february 15|on
rushed|jackson|obj
rushed|hospital|to
hospital|flu|with
rushed|delaying|mod
delaying|jackson|subj
selection|jury|nn
delaying|selection|obj
trial|his|gen
selection|trial|in
days|3-4|amount-value
jackson|days|nn
delaying|left|mod
left|jackson|subj
left|hospital|obj
left|after|mod
being|there|guest
hours|33|amount-value
being|hours|pred
hours|february 23|on
after|selected|comp1
selected|jury|obj
selected|after|mod
after|sworn in|comp1
sworn in|jury|obj
began|attorneys|subj
began|selection|obj
jurors|eight|nn
jurors|alternate|nn
selection|jurors|of
jurors|february 28|on
judge|trial|mod
revealed|judge|subj
revealed|detail|obj
detail|charges|of
charges|jackson|against
revealed|and|punc
revealed|read|conj
read|judge|subj
read|indictment|obj
indictment|that|whn
accused|indictment|subj
accused|jackson|obj
jackson|molesting|of
molesting|judge|subj
molesting|13 year old|obj
neverland ranch|his|gen
13 year old|neverland ranch|at
neverland ranch|2003|in
