michael jackson|november 2003|nn
michael jackson|police|nn
michael jackson|arrested|mod
accused|michael jackson|in
michael jackson|counts|on
molestation|child|nn
counts|molestation|of
molestation|raided|after
raided|his|obj
jackson|california|nn
jackson|ranch|nn
attorney|jackson|gen
accused|attorney|subj
attorney|district|nn
accused|attorney|obj
attorney|having|of
having|attorney|subj
having|vendetta|obj
vendetta|jackson|against
having|and|punc
having|alleged|conj
alleged|attorney|subj
alleged|in|guest
alleged|lawsuit|in
alleged|that|c
conversations|private|mod
conversations|used|vrel
used|conversations|obj
used|as|mod
as|been|comp1
recorded|illegally|mod
jackson|recorded|mod
been|jackson|pred
had|conversations|subj
had|problems|obj
rapper eminem|his|gen
rapper eminem|legal|mod
rapper eminem|team|nn
problems|rapper eminem|with
rapper eminem|issued|vrel
issued|rapper eminem|obj1
issued|video|obj2
video|showing|rel
showing|video|subj
showing|jackson|obj1
showing|look-alike|obj2
look-alike|bed|on
bed|children|with
associate|former|mod
associate|business|mod
associate|seeking|rel
seeking|associate|subj
seeking|$3 million|obj
$3 million|sued|vrel
sued|$3 million|obj
sued|breach of contract|for
breach of contract|and|punc
breach of contract|merchant|conj
merchant|sued|vrel
sued|merchant|obj
sued|collect|mod
collect|nearly $180,000|obj
investigators|december 2003|nn
nearly $180,000|investigators|in
searched|associate|subj
ranch|jackson|gen
searched|ranch|obj
searched|and|punc
searched|took|conj
took|associate|subj
took|dna|obj
mouth|his|gen
dna|mouth|from
