29|nearly|num-mod
steve fossett|29|nn
steve fossett|flight|nn
steve fossett|hours|nn
after|reached|comp1
reached|steve fossett|subj
point|his|gen
point|halfway|mod
reached|point|obj
point|india|over
reached|while|mod
relying on|steve fossett|subj
relying on|autopilot|obj
could|not|neg
while|ignore|comp1
ignore|he|subj
demands|complex|mod
ignore|demands|obj
demands|aircraft|of
10-20|more than|num-mod
minutes|10-20|amount-value
aircraft|minutes|for
minutes|time|at
time|wednesday|on
mission|mainland|nn
mission|china|nn
flying over|mission|obj
officials|control|nn
reported|officials|subj
fuel|his|gen
reported|was|fc
gallons|450|amount-value
was|gallons|pred
was|less|mod
was|than|mod
fossett|expected|mod
than|decided|comp1
decided|fossett|subj
fly|fossett|subj
fly|hawaii|to
hawaii|re|rel
re|hawaii|subj
re|situation|obj
re|there|mod
decided|decided|fc
decided|he|subj
proceed|he|subj
stream|jet|nn
stream|and|punc
tailwinds|great|mod
stream|tailwinds|conj
tailwinds|pacific|over
decided|allowed|fc
allowed|stream|subj
make|him|subj
make|up|guest
make|time|up
time|made|rel
made|time|obj
made|fossett|subj
landing|perfect|mod
make|landing|obj
landing|salina kansas|in
flight|67-hour|nn
salina kansas|flight|after
