left|steve fossett|subj
evening|monday|nn
left|evening|mod
left|salina|from
salina|solo|on
flight|nonstop|mod
flight|non-refueled|mod
flight|world|around
flyer|global|mod
world|flyer|in
flyer|estimated|rel
estimated|flyer|obj
estimated|he|subj
time|flying|mod
estimated|time|mod
hours|60-80|amount-value
estimated|hours|at
hours|took off|rel
took off|hours|obj
took off|he|subj
took off|6:47|at
was|concerned|pred
moment|brief|mod
concerned|moment|for
was|when|wha
lose|plane|subj
seconds|altitude|nn
lose|seconds|obj
lose|after|mod
taking|plane|subj
taking|off|mod
pm|10|num
off|pm|by
after|approached|comp1
approached|he|subj
airspace|canadian|mod
approached|airspace|obj
approached|and|punc
approached|soared|conj
soared|he|subj
soared|atlantic ocean|toward
soared|while|mod
flying|plane|subj
flying|across|mod
gps|canada fossett|gen
while|malfunctioned|comp1
malfunctioned|gps|subj
malfunctioned|couple|after
couple|hours|of
corrected|gsp|subj
corrected|itself|obj
usage|monitoring|nn
usage|fuel|nn
challenge|critical|mod
was|challenge|pred
challenge|flight|during
flight|flew|rel
flew|flight|obj
flew|fossett|subj
flew|africa|over
africa|and|punc
africa|middle east|conj
middle east|tuesday|on
