real id act|enacted|vrel
enacted|real id act|obj
enacted|may 2005|in
required|real id act|subj
years|three|amount-value
states|years|nn
determine|states|in
required|determine|fc
determine|that|subj
applicants|driver 's license|nn
are|in|guest
are|country|in
civil|legally|mod
libertarians|civil|mod
are|libertarians|pred
libertarians|and|punc
rights|immigration|nn
libertarians|rights|conj
determine|protested|fc
protested|activists|subj
states|bill|nn
protested|blasted|fc
blasted|states|subj
blasted|bill|obj
blasted|because|mod
because|placed|comp1
placed|it|subj
burden|large|mod
placed|burden|obj
burden|them|on
them|and|punc
them|worker|conj
worker|training|rel
training|worker|subj
training|requirements|obj
requirements|believed|comp1
believed|they|subj
underestimated|grossly|mod-before
believed|underestimated|fc
underestimated|act|subj
demands|financial|mod
financial|logistical|conj
logistical|and|punc
logistical|technological|conj
underestimated|demands|obj
demands|need|rel
need|demands|obj
need|states|subj
need|amend|mod
amend|state|subj
laws|their|gen
amend|laws|obj
laws|and|punc
need|others|nn
laws|need|conj
systems|their|gen
systems|computing|nn
overhaul|systems|obj
systems|verify|rel
verify|system|subj
verify|accuracy|obj
accuracy|documents|of
phased in|bill|obj
period|5-year|nn
phased in|period|over
phased in|beginning|mod
beginning|bill|subj
beginning|2008|in
