sec|and|punc
sec|justice department|conj
studied|sec|subj
handling|merck|gen
handling|vioxx merck|of
studied|was|fc
was|unsure|pred
insurance|their|gen
be|adequate|pred
adequate|lawsuits|against
unsure|dropped|fc
dropped|moody 's|subj
rating|merck|gen
rating|credit|nn
dropped|rating|obj
exposure|litigation|nn
rating|exposure|because of
trial|clinical|mod
trial|celebrex|of
celebrex|drug|appo
drug|similar|pnmod
similar|vioxx|to
shut|trial|obj
shut|down|mod
shut|when|wha
found|researchers|subj
risk|increased|mod
found|risk|obj1
disease|heart|nn
risk|disease|of
disease|and|punc
disease|stroke|conj
stroke|heard|rel
heard|stroke|obj
heard|senate committee|subj
found|testimony|obj2
testimony|that|c
merck|and|punc
merck|fda|conj
were|aware|pred
aware|of|guest
risks|vioxx|nn
aware|risks|of
before|approved|comp1
approved|drug|obj
aware|adopted|fc
adopted|merck|subj
adopted|plan|obj
plan|protect|comp1
protect|merck|subj
protect|230|obj
executives|their|gen
executives|top|nn
230|executives|of
protect|in case|mod
trouble|financial|mod
in case|necessitated|comp1
necessitated|trouble|subj
necessitated|takeover|obj
