withdrew|merck|subj
withdrew|vioxx|obj
withdrew|when|wha
showed|study|subj
showed|increased|fc
increased|it|subj
increased|risk|obj
risk|strokes|of
strokes|and|punc
attacks|heart|nn
strokes|attacks|conj
study|fda|nn
attacks|estimates|rel
estimates|study|subj
estimates|caused|fc
caused|vioxx|subj
attacks/deaths|27,785|num
caused|attacks/deaths|obj2
approval|its|gen
attacks/deaths|approval|since
was|concerned|pred
concerned|use|about
use|related|mod
use|drug|nn
use|use|of
was|and|punc
was|sought|conj
sought|medical community|subj
guidance|more|mod
sought|guidance|obj
thousands|lawyers|nn
thousands|estimated|mod
thousands|lawsuits|of
filed|thousands|obj
filed|merck|against
estimate|one|nn
estimate|settlement|nn
was|$12 billion|pred
costs|merck|gen
$12 billion|withdraw|rel
withdraw|costs|subj
vioxx|market|from
were|$552.6 million|pred
profits|their|gen
profits|third quarter|for
third quarter|2004|of
profits|dropped|vrel
dropped|profits|obj1
medical reports|29 percent|nn
dropped|medical reports|obj2
criticized|profits|subj
failing|merck|gen
criticized|failing|obj
failing|stop|rel
stop|failing|subj
stop|vioxx|obj
stop|when|wha
showed|first|mod-before
showed|data|subj
danger|its|gen
danger|potential|mod
showed|danger|obj
