declared|hurricane rita|as
hurricane rita|moved|vrel
moved|hurricane rita|obj
keys|florida|nn
moved|keys|toward
18 september|sunday|nn
keys|18 september|on
governor|florida|nn
declared|governor|subj
monday|emergency|mod
state|monday|of
state|residents|conj
residents|and|punc
residents|tourists|conj
declared|told|fc
told|state|obj
told|evacuate|fc
evacuate|state|subj
keys|florida|nn
evacuate|keys|obj
afternoon|early|mod
afternoon|tuesday|nn
keys|afternoon|by
strengthened|rita|subj
storm|category|nn
storm|two|nn
strengthened|storm|to
strengthened|winds|with
mph|100|num
winds|mph|of
strengthened|and|punc
strengthened|expected|conj
gain|rita|subj
strength|further|mod
gain|strength|obj
gain|and|punc
gain|reach|conj
reach|rita|subj
three|category|nn
reach|three|obj1
three|it|as
reach|hit|obj2
residents|warm|mod
residents|gulf of mexico|nn
residents|waters|nn
residents|new orleans|of
hit|evacuating|rel
evacuating|hit|obj
evacuating|residents|subj
governor|louisiana|nn
declared|governor|subj
state|emergency|of
louisiana galveston|western|mod
emergency|louisiana galveston|in
declared|expected|fc
order|hit|obj1
order|state|subj
evacuation|mandatory|mod
order|evacuation|obj2
21 september|wednesday|nn
evacuation|21 september|on
