attached|real id act|obj
bill|2005|num
bill|must-pass|nn
bill|iraq appropriations|nn
attached|bill|to
bypassing|hearings|obj
hearings|and|punc
hearings|debate|conj
debate|contains|rel
contains|debate|obj
contains|act|subj
provisions|aimed at|vrel
aimed at|provisions|obj
aimed at|keeping|mod
keeping|terrorists|obj1
terrorists|crossing|from
borders|us|nn
crossing|borders|obj
controversial|most|mod
keeping|controversial|desc
make|provisions|subj
make|it|obj
make|hard|mod
hard|states|for
states|issue|rel
issue|state|subj
issue|driver 's licenses|obj
immigrants|illegal|mod
driver 's licenses|immigrants|to
issue|and|punc
require|possibly|amod
issue|require|conj
require|state|subj
id|national|mod
require|id|obj
states|card|nn
need|states|subj
need|add|fc
add|state|subj
features|security|nn
add|features|obj
features|driver 's licenses|to
add|and|punc
add|create|conj
create|state|subj
databases|license|nn
create|databases|obj
databases|detested|rel
detested|databases|obj
detested|americans|subj
idea|tried|comp1
tried|aclu|subj
tried|stop|fc
stop|aclu|subj
opponents|bill|nn
stop|opponents|obj
viewed|idea|subj
viewed|it|obj
attack|blatant|mod
viewed|attack|as
rights|immigrants|gen
attack|rights|on
viewed|and|punc
did|not|neg
viewed|believe|conj
believe|idea|subj
believe|improve|fc
improve|it|subj
security|us|nn
improve|security|obj
