upgraded|winds|with
mph|115|num
winds|mph|of
upgraded|rita|obj
royal dutch shell|level|mod
royal dutch shell|three|nn
royal dutch shell|hurricane|nn
upgraded|royal dutch shell|to
evacuated|bp|subj
evacuated|all|guest
personnel|non-essential|mod
evacuated|personnel|obj
facilities|off-shore|mod
personnel|facilities|from
evacuated|later|mod
evacuated|day|mod
day|upgraded|comp1
upgraded|storm|obj
five|category|nn
upgraded|five|to
five|winds|with
mph|165|num
winds|mph|of
state|emergency|of
declared|state|obj
declared|texas|in
evacuations|louisiana mandatory|nn
ordered|evacuations|obj
ordered|new orleans|for
new orleans|and|punc
new orleans|galveston|conj
one million|over|num-mod
people|one million|nn
people|asked|rel
asked|people|obj2
asked|coast|obj1
asked|evacuate|mod
evacuate|coast|subj
evacuate|voluntarily|mod
troops|320,000|num
troops|national guard|nn
voluntarily|troops|about
mobilized|people|obj
path|hurricane|of
uncertain|still|mod
was|uncertain|pred
hit|it|subj
hit|texas|obj
texas|or|punc
texas|louisiana|conj
