hosted|yusuf islam|subj
concert|benefit|nn
hosted|concert|obj
relief|tsunami|nn
concert|relief|for
relief|jakarta|in
jakarta|january 2005|in
hosted|and|punc
hosted|recorded|conj
recorded|yusuf islam|subj
recorded|song|obj
song|indian ocean|title
song|"|punc
song|provide|rel
provide|song|subj
provide|aid|obj
children|tsunami|nn
children|orphaned|mod
aid|children|to
kindness|his|gen
kindness|charity|nn
kindness|small|nn
children|set up|rel
set up|children|obj
set up|kindness|subj
office|indonesia|in
indonesia|assist|rel
assist|indonesia|subj
islam|orphans|nn
assist|islam|obj
said|office|subj
said|in|guest
said|february 2005|in
said|that|c
work|his|gen
affected|adversely|mod
was|affected|pred
was|when|wha
newspapers|two|nn
newspapers|british|mod
alleged|newspapers|subj
alleged|involved|fc
involved|he|obj
involved|terrorism|in
terrorism|apologized|rel
apologized|terrorism|obj
apologized|newspapers|subj
involved|paid|conj
paid|he|subj
legal fees|his|gen
paid|legal fees|obj
paid|and|punc
paid|promised|conj
promised|he|obj
promised|repeat|fc
repeat|he|subj
repeat|allegations|obj
allegations|year|guest
after|barred|comp1
barred|he|obj
entering|he|subj
entering|us|obj
revealed|not|amod
allegations|revealed|comp1
revealed|government|subj
reason|its|gen
revealed|reason|obj
reason|doing|for
revealed|so|mod
