having|michael jackson|subj
time|rough|mod
having|time|obj
attorney|his|gen
attorney|long-time|nn
attorney|steve cochran|person
time|left|comp1
left|attorney|subj
team|defense|nn
left|team|obj
reasons|unknown|mod
team|reasons|for
reasons|made|rel
made|reasons|obj1
made|eminem|subj
video|music|nn
made|video|desc
video|showing|rel
showing|video|subj
look-alike|jackson|nn
showing|look-alike|obj
look-alike|bed|in
bed|children|with
showing|sued|fc
sued|he|obj
sued|three million dollars|for
associate|former|mod
associate|business|mod
three million dollars|associate|by
associate|breach of contract|for
for|and|punc
for|for|conj
for|$180,000|for
store|antique|mod
$180,000|store|by
bills|unpaid|mod
bills|and|punc
bills|canadian|conj
pleaded|bills|subj
pleaded|guilty|desc
guilty|emailing|to
emailing|bill|subj
emailing|death|obj1
emailing|threat|obj2
made|jackson another|to
threat|made|comp1
made|search|obj
neverland ranch|jackson|gen
made|neverland ranch|of
neverland ranch|3 december|on
day|following|mod
took|investigators|subj
samples|dna|nn
took|samples|obj
mouth|jackson|gen
samples|mouth|from
