introduced|10 january|on
months|six|amount-value
10 january|months|appo
months|ahead|pnmod
ahead|schedule|of
introduced|apple|subj
computers|two|nn
computers|new|mod
computers|intel-based|mod
introduced|computers|obj
computers|imac|conj
imac|and|punc
imac|laptop|conj
laptop|called|vrel
called|laptop|obj1
pro|macbook|nn
called|pro|desc
imac|new|mod
times|two to three|amount-value
is|times|pred
times|faster|pnmod
model|old|mod
faster|model|than
is|while|mod
while|is|comp1
times|four to five|amount-value
is|times|pred
is|faster|mod
is|although|mod
although|cost|comp1
cost|they|subj
cost|same|obj
cost|as|mod
developers|old|mod
developers|models|nn
developers|software|nn
as|working on|comp1
working on|developers|subj
working on|programs|obj
programs|that|whn
run|programs|subj
on|both|punc
run|intel|on
intel|and|punc
macs|older|mod
intel|macs|conj
run|although|mod
inside|processors|nn
although|are|comp1
are|same|pred
same|those|as
those|used|vrel
used|those|obj
pcs|windows-based|mod
used|pcs|on
macs|new|mod
will|not|neg
be|able|pred
be|run|mod
run|mac|subj
software|windows|nn
run|software|obj
