rita|tropical|mod
rita|storm|nn
appeared|rita|subj
appeared|likely|mod
appeared|upgraded|mod
hurricane|category 1|nn
upgraded|hurricane|to
upgraded|before|mod
passing|florida|obj
governor|keys|nn
governor|florida|nn
before|declared|comp1
declared|governor|subj
declared|state|obj
state|emergency|of
emergency|enabling|rel
enabling|emergency|subj
enabling|him|obj
enabling|oversee|mod
oversee|evacuations|obj
oversee|and|punc
oversee|activate|conj
activate|national guard|obj
us national hurricane center|warned|vrel
warned|us national hurricane center|obj
warned|that|c
threaten|rita|subj
threaten|texas|obj
texas|and|punc
texas|louisiana|conj
governor|days|nn
governor|louisiana|nn
louisiana|governor|within
declared|us national hurricane center|subj
declared|state|obj
state|emergency|of
emergency|worked|rel
worked|emergency|obj
worked|new orleans|subj
worked|bolster|mod
bolster|new orleans|subj
levees|weakened|mod
bolster|levees|obj
bolster|and|punc
bolster|establish|conj
establish|new orleans|subj
rita|military hospital|nn
establish|upgraded|fc
upgraded|rita|obj
upgraded|category 2|to
worked|and|punc
worked|expected|conj
expected|new orleans|subj
reach|new orleans|subj
reach|category 3|obj1
category 3|gulf along|in
refugees|gulf|nn
refugees|coast|nn
reach|refugees|obj2
expected|were|fc
schools|and|punc
schools|offices|conj
closed|schools|obj
