reached|fossett|subj
point|half-way|mod
reached|point|obj
point|flying over|while
flying over|fossett|subj
flying over|india|obj
picked up|also|mod-before
picked up|he|subj
boost|100|num
boost|mph|nn
boost|jet stream|nn
picked up|boost|obj
picked up|while|mod
while|was|comp1
was|over|pred
was|china|over
officials|mission|nn
officials|control|nn
concluded|officials|subj
concluded|that|c
had|he|subj
had|fuel|obj
had|than|mod
than|counted|comp1
counted|they|subj
decided|this|despite
decided|fossett|subj
press on|fossett|subj
press on|hawaii|to
legs|final|mod
hawaii|legs|on
flight|his|gen
legs|flight|of
decided|stayed|fc
stayed|fossett|subj
stayed|awake|desc
awake|drinking|by
drinking|fossett|subj
hours|dozen|mod
hours|chocolate|mod
hours|protein|nn
hours|milkshakes|nn
hours|slightly|nn
67|over|num-mod
hours|67|amount-value
drinking|hours|obj
hours|departure|after
departure|salina|from
landed|fossett|subj
landed|global flyer|obj
airstrip|same|post
global flyer|airstrip|on
departed|which|obj
departed|he|subj
had|plane|subj
fuel|enough|mod
had|fuel|obj
fuel|remaining|rel
remaining|fuel|subj
remaining|fly|mod
fly|plane|subj
10|another|num-mod
hours|10|amount-value
fly|hours|obj
