president|mexico|gen
condemned|president|subj
condemned|real id act|obj
condemned|including|mod
including|president|subj
including|provisions|obj
waived|construction|for
construction|wall|of
border|common|mod
wall|border|along
provisions|waived|comp1
waived|homeland security|subj
laws|environmental|mod
waived|laws|obj
waived|real id act|as
completion|authorized|mod
states|border|nn
states|fence|nn
completion|states|of
finding|completion|subj
demands|financial|mod
financial|logistical|conj
logistical|and|punc
logistical|technical|conj
demands|law|of
law|daunting|rel
daunting|law|subj
effect|possible|mod
effect|unintended|mod
daunting|effect|obj
finding|increased|fc
increased|demands|obj
california|unlicensed|mod
california|uninsured|mod
california|motorists|nn
opted|california|subj
opted|offer|fc
offer|california|subj
licenses|illegal|mod
licenses|immigrants|nn
licenses|separate|mod
offer|licenses|obj1
licenses|driving|for
driving|only|mod
driving|used|mod
used|official|as
offer|identification|obj2
identification|broadening|by
broadening|definition|obj
groups|terrorist|mod
definition|groups|of
complicated|real id act|subj
complicated|laws|obj
laws|regarding|rel
regarding|law|subj
regarding|refugees|obj
refugees|resettling|rel
resettling|refugee|subj
resettling|us|in
