investigators|international|nn
uncovered|investigators|subj
uncovered|evidence|obj
evidence|showing|rel
showing|evidence|subj
showing|that|c
agreed|q.a khan|subj
agreed|sell|fc
sell|q.a khan|subj
sell|iran|obj1
program|nuclear weapons|nn
sell|program|obj2
sell|18 years ago|mod
sell|february 2005|in
february 2005|reported|rel
reported|time|subj
reported|that|c
investigating|february 2005|obj
investigating|us|subj
investigating|whether|c
sold|qa khan|subj
technology|nuclear|mod
sold|technology|obj
technology|saudi arabia|to
saudi arabia|and|punc
countries|other|mod
saudi arabia|countries|conj
played|also|amod
played|february 2005|obj
played|khan|subj
role|bigger|mod
role|helping|in
helping|north korea|obj
programs|nuclear|mod
north korea|programs|with
reported|previously|amod
reported|role|obj
said|article|subj
said|suspects|fc
suspects|us|subj
suspects|did|fc
did|khan|subj
did|business|obj
business|al-qaeda|with
pakistan|lacks|nn
pakistan|concrete|mod
pakistan|evidence|nn
dismissed|pakistan|subj
dismissed|article|obj
article|as|mod
dismissed|facts|without
full|distortion|of
