countries|including|rel
including|country|subj
including|ireland|obj
rwanda|and|punc
rwanda|eritrea|conj
banned|either|mod
bags|banned|mod
bags|plastic|mod
have|bags|obj
have|or|punc
have|charged|conj
charged|fee|obj
use|their|gen
fee|use|for
charged|after|mod
after|imposed|comp1
imposed|ireland|subj
imposed|fee|obj
fee|15 cents|of
usage|their|gen
usage|dropped|vrel
dropped|usage|obj
dropped|by|by-subj
dropped|90%|by
owners|rwandan|mod
owners|shop|nn
90%|resorted to|rel
resorted to|90%|obj
resorted to|owners|subj
making|usage|subj
making|bags|obj
bags|newspapers|out of
been|slow|pred
been|do|mod
do|u.s.|subj
do|anything|obj
anything|considering|rel
considering|anything|obj
considering|san francisco|subj
considering|charging|mod
charging|san francisco|subj
move|17 cents a bag-a|mod
charging|move|obj
move|opposed|vrel
opposed|move|obj
opposed|by|by-subj
opposed|grocers|by
grocers|and|punc
industry|plastic|mod
grocers|industry|conj
industry|considering|rel
considering|industry|obj1
considering|los angeles|subj
force|task|nn
considering|force|obj2
force|consider|rel
consider|force|subj
consider|ways|obj
ways|collect|rel
collect|way|subj
collect|and|punc
collect|recycle|conj
recycle|way|subj
recycle|bags|obj
recycle|and|punc
recycle|implement|conj
implement|way|subj
campaigns|public|mod
campaigns|education|nn
implement|campaigns|obj
