announced|sandra day o 'connor|subj
announced|that|c
retiring|she|subj
retiring|supreme court|from
supreme court|effective|pnmod
effective|confirmation|upon
successor|her|gen
confirmation|successor|of
retiring|minutes|mod
retiring|after|mod
political leaders|announcement|nn
political leaders|and|punc
groups|lobby|nn
political leaders|groups|conj
groups|prepared|vrel
prepared|groups|obj
liberals|ensuing|mod
liberals|battle|nn
prepared|liberals|for
did|not|neg
after|want|comp1
want|political leaders|subj
extremist|"|punc
want|extremist|obj
wanted|republicans|subj
wanted|judge|obj
judge|who|whn
apply|judge|subj
apply|rather|mod
president|constitution|nn
choice|president|gen
president|bush|person
choice|judge|of
was|important|pred
cases|key|mod
important|cases|because of
cases|abortion|in
suicide|assisted|mod
suicide|and|punc
one|gay|mod
one|rights|nn
suicide|one|conj
one|difficulties|of
difficulties|nominating|in
nominating|judge|obj
is|that|c
do|not|neg
vote|always|amod
vote|they|subj
one|way|nn
vote|one|obj
affiliation|their|gen
affiliation|political|mod
affiliation|or|punc
affiliation|ideology|conj
