health|yasser arafat|gen
declined|health|subj
october|late|mod
declined|october|in
flown|he|obj
hospital|military|nn
flown|hospital|to
hospital|paris|outside
29 october|friday|nn
paris|29 october|on
paris|wednesday|on
transferred|he|obj
unit|intensive|mod
unit|care|nn
transferred|unit|to
transferred|since|mod
there|then|mod
since|conflicting|comp1
conflicting|there|subj
about|whether or not|c
died|he|subj
plans|funeral|nn
were|under|pred
were|discussion|under
factions|13|num
factions|main|mod
factions|palestinian|mod
factions|met|vrel
met|factions|obj
met|tuesday|on
tuesday|discuss|rel
discuss|tuesday|subj
egypt|arrangements|nn
discuss|egypt|obj
host|factions|subj
france|funeral|nn
france|services|nn
host|france|obj
france|reached|vrel
reached|france|obj1
reached|agreement|obj2
agreement|israel|with
israel|arafat|for
arafat|buried|rel
headquarters|his|gen
buried|headquarters|at
headquarters|ramallah israel|in
ramallah israel|refused|vrel
refused|ramallah israel|obj
refused|allow|mod
buried|him|obj
buried|jerusalem|in
