owners|league|nn
owners|baseball|nn
approved|owners|subj
approved|relocation|obj
relocation|montreal expos|of
montreal expos|washington|to
government|dc|nn
provide|government|subj
provide|funding|obj
ballpark|new|mod
funding|ballpark|for
ballpark|31 december|by
reached|agreement|obj
reached|22 december|on
stadium|400-million-dollar|mod
reached|stadium|for
nationals|new|mod
nationals|washington|nn
stadium|play|rel
play|stadium|obj
play|nationals|subj
play|rfk stadium|in
play|until|mod
ballpark|new|mod
until|built|comp1
built|ballpark|obj
won|nationals|subj
game|their|gen
game|first|post
game|exhibition|nn
game|florida|in
florida|22 march|on
defeating|game|subj
5-3|ny|nn
5-3|mets|nn
defeating|5-3|obj
defeating|and|punc
defeating|scheduled|conj
scheduled|game|obj
scheduled|make|mod
make|game|subj
debut|their|gen
debut|dc|nn
make|debut|obj
game|exhibition|nn
debut|game|in
game|mets|against
stadium|rfk|nn
mets|stadium|at
stadium|3 april|on
