reported|february 2005|in
magazine|time|nn
reported|magazine|subj
reported|that|c
provided|also|mod-before
provided|a. q. khan|subj
equipment|nuclear|mod
provided|equipment|obj
equipment|saudi arabia|to
saudi arabia|and|punc
nations|other|mod
nations|arab|nn
saudi arabia|nations|conj
nations|stated|rel
stated|it|subj
stated|that|c
earned|nations|obj
earned|khan|subj
earned|up|mod
up|$400 million|to
$400 million|and|punc
$400 million|his|conj
active|still|mod
was|active|pred
reported|also|mod-before
reported|magazine|subj
reported|that|obj
cylinders|gas|of
gas|critical|pnmod
enrichment|uranium|nn
critical|enrichment|to
laboratory|pakistani|mod
laboratory|nuclear|mod
called|laboratory|from
officials|pakistani|mod
called|officials|subj
called|report|obj
campaign|disinformation|nn
part|campaign|of
