lawyer|austin|nn
shot|accidentally|mod-before
lawyer|shot|vrel
shot|lawyer|obj
shot|by|by-subj
shot|president|by
president|cheney|person
suffered|lawyer|subj
attack|minor|mod
attack|heart|nn
suffered|attack|obj
suffered|february 14|mod
suffered|result|as
result|birdshot|of
heart|his|gen
birdshot|heart|in
heart|is|rel
condition|stable|mod
is|condition|in
is|and|punc
expected|still|amod
is|expected|conj
recover|fully|amod
recover|heart|obj
recover|he|subj
are|optimistic|pred
cause|pellet|subj
problems|future|mod
cause|problems|obj1
cheney|democrats|nn
cheney|accused|nn
cause|cheney|obj2
cheney|pattern|of
pattern|secrecy|of
delay|his|gen
secrecy|delay|for
delay|reporting|in
reporting|pellet|subj
reporting|incident|obj
incident|spoke|rel
spoke|incident|obj
spoke|he|subj
spoke|incident|about
incident|interview|in
interview|february 15|on
calling|day|guest
calling|one|obj
one|worst|of
life|his|gen
worst|life|of
calling|and|punc
calling|accepting|conj
blame|full|mod
accepting|blame|obj
blame|accident|for
sheriff|texas|nn
cheney|office|nn
cheney|cleared|mod
's|cheney|pred
cheney|wrongdoing|of
wrongdoing|incident|in
