lay|arafat|subj
lay|coma|in
coma|hospital|at
hospital|week|for
lay|and|punc
lay|died|conj
died|arafat|subj
gmt|0230|num
died|gmt|at
gmt|thursday|on
cause|10 november|nn
cause|death|of
given|cause|obj
declared|palestinian authority|subj
period|40-day|nn
declared|period|obj
period|mourning|of
mourning|palestinian authority|subj
businesses|private|mod
mourning|businesses|with
businesses|closed|vrel
closed|businesses|obj
days|three|amount-value
closed|days|for
institutions|public|mod
arafat|seven|nn
institutions|arafat|for
was|flown|pred
flown|cairo|to
cairo|funeral|for
funeral|attended|rel
attended|friday|obj
attended|by|by-subj
attended|arab|by
arab|and|punc
leaders|international|mod
arab|leaders|conj
leaders|then|person
body|his|gen
was|flown|pred
flown|ramallah|to
ramallah|burial|for
israel|presidential|mod
israel|compound|nn
burial|israel|in
israel|sealed|vrel
sealed|israel|obj
sealed|west bank|off
west bank|and|punc
west bank|gaza strip|conj
sealed|and|punc
sealed|tightened|conj
tightened|israel|subj
tightened|security|obj
security|"|punc
security|allow|rel
allow|security|subj
ceremony|dignified|mod
ceremony|funeral|nn
allow|ceremony|obj
