dissemination|yasser arafat|gen
dissemination|wife|nn
dissemination|controlled|mod
dissemination|information|of
reports|his|gen
reports|health|nn
information|reports|about
differed|dissemination|subj
differed|severity|on
illness|his|gen
severity|illness|of
was|alive|pred
transferred|he|obj
hospital|french|nn
hospital|military|nn
transferred|hospital|to
hospital|paris|near
condition|his|gen
deteriorated|later|mod-before
deteriorated|condition|subj
went into|suddenly|mod-before
went into|he|subj
coma|deep|mod
went into|coma|obj
seemed|death|subj
seemed|imminent|desc
sources|palestinian|mod
said|sources|subj
said|buried|fc
buried|he|obj
said|west bank ariel sharon|subj
said|buried|fc
buried|he|obj
host|gaza egypt|subj
israeli|funeral|nn
israeli|services|nn
host|israeli|obj
israeli|and|punc
officials|palestinian|mod
israeli|officials|conj
officials|met|vrel
met|officials|obj
met|discuss|mod
discuss|gaza egypt|subj
arrangements|funeral|nn
discuss|arrangements|obj
met|but|punc
would|not|neg
met|reveal|conj
reveal|officials|subj
reveal|them|obj
