were|13 april|as of
were|tied|pred
tied|first|for
division|their|gen
first|division|in
division|won|rel
won|they|subj
opening|division|obj1
opening|their|subj
game|home|nn
opening|game|obj2
5-3|arizona|over
stadium|sold-out|mod
arizona|stadium|before
before|and|punc
before|by|conj
before|11 june|by
had|5-3|subj
had|won 10|obj
games|11|num
won 10|games|of
had|more|mod
had|than|mod
tickets|22,000|num
tickets|season|nn
than|sold|comp1
sold|tickets|obj
make|team|subj
profit|pre-tax|mod
make|profit|obj
profit|$20 million|of
$20 million|its|in
season|first|post
been|strong|pred
problems|legal|mod
limited|problems|subj
exposure|their|gen
exposure|television|nn
limited|exposure|obj
exposure|protested|rel
protested|exposure|obj
protested|washingtonians|subj
be|spent|pred
schools|new|mod
spent|schools|on
schools|not|appo-mod
schools|stadium|appo
