scientist|nuclear|mod
was|scientist|pred
scientist|who|whn
oversaw|scientist|subj
oversaw|spread|obj
spread|nuclear weapons|of
nuclear weapons|us|to
khan|adversaries|nn
did|khan|subj
did|more|obj
more|undermine|rel
undermine|more|subj
causes|us|nn
undermine|causes|obj
causes|bin laden|than
undermine|confessed|mod
confessed|to|guest
technology|nuclear weapons|nn
confessed|technology|obj
technology|iran|to
iran|libya|conj
libya|and|punc
libya|north korea|conj
officials|november 2004|nn
officials|us|nn
north korea|officials|in
officials|and|punc
officials|un|conj
searching|still|amod
north korea|searching|rel
searching|north korea|obj
searching|iaea|subj
searching|for|mod
countries|other|mod
countries|khan|with
for|digitized|comp1
digitized|countries|subj
digitized|blueprints|obj
equipment|nuclear|mod
equipment|manufacturing|nn
blueprints|equipment|for
equipment|and|punc
user|uranium|nn
user|enrichment|nn
user|centrifuges|nn
equipment|user|conj
khan|manuals|nn
network|khan|gen
user|spread|rel
spread|user|obj
spread|network|subj
lives|30|num
lives|countries|nn
lives|khan|nn
granted|lives|across
arrest|house|nn
lives|arrest|under
arrest|islamabad|in
granted|he|obj1
pardon|full|mod
granted|pardon|obj2
granted|and|punc
granted|allowed|conj
keep|he|subj
keep|money|obj
money|believed|vrel
believed|money|obj
be|from|pred
sales|illicit|mod
be|sales|from
