minister|palestinian|mod
minister|state|of
said|minister|subj
body|arafat|gen
said|brought|fc
brought|body|obj
brought|cairo|to
cairo|where|wha
leaders|world|nn
pay|leaders|subj
respects|their|gen
pay|respects|obj
then|west bank|to
funeral|his|gen
west bank|funeral|for
hospital|where|wha
lain|arafat|subj
lain|coma|in
confirmed|hospital|subj
confirmed|that|c
died|he|subj
died|november 11|on
died|3:30 am|at
authorities|gave|mod
authorities|details|nn
authorities|palestinian|mod
declared|authorities|subj
period|40-day|nn
period|mourning|mod
declared|period|obj
period|and|punc
businesses|ordered|mod
period|businesses|conj
businesses|close|rel
close|business|subj
days|three|amount-value
hours|days|nn
close|hours|for
close|after|mod
israel|arafat|gen
israel|death|nn
after|sealed|comp1
sealed|israel|subj
tightened|west bank|off
west bank|and|punc
strip|gaza|nn
west bank|strip|conj
sealed|tightened|fc
tightened|they|subj
tightened|security|obj
settlements|jewish|mod
security|settlements|at
tightened|before|mod
palestinians|funeral|nn
palestinians|only|mod
palestinians|permits|with
before|allowed|comp1
attend|palestinians|subj
funeral|arafat|gen
attend|funeral|obj
