crash|train|nn
crash|glendale|in
glendale|26 january|on
killed|crash|subj
people|11|num
killed|people|obj
killed|and|punc
killed|injured|conj
injured|crash|subj
200|close to|num-mod
injured|200|obj
train|southbound|mod
train|commuter|nn
hit|by|mod-before
hit|locomotive|by
hit|suv|obj
suv|lodged|vrel
lodged|suv|obj
lodged|tracks|on
hit|then|amod
tracks|hit|vrel
hit|tracks|obj1
train|freight|nn
hit|train|obj2
train|and|punc
juan manuel alvarez|northbound|mod
juan manuel alvarez|commuter train|nn
juan manuel alvarez|police|nn
juan manuel alvarez|arrested|mod
train|juan manuel alvarez|conj
driver|suv|of
suv|who|whn
jumped|suv|subj
jumped|car|from
jumped|just|mod
just|impact|before
impact|first|at
wounds|self-inflicted|mod
wrists|his|gen
wounds|wrists|on
wrists|and|punc
wrists|chest|conj
led|wounds|subj
led|investigators|obj
investigators|think|rel
think|investigator|subj
think|that|c
suicide|attempted|mod
was|suicide|pred
suicide|was|rel
was|determined|pred
determined|later|guest
determined|that|c
got|suicide|obj1
got|he|subj
got|wounds|obj2
got|after|mod
after|fled|comp1
fled|he|subj
fled|scene|obj
