probe|european-built|mod
probe|huygens|nn
probe|space|nn
probe|landed|vrel
landed|safely|mod
surface|titan|gen
safely|surface|on
landed|as|mod
controllers|january 14|nn
controllers|mission|nn
scheduled|controllers|on
were|confident|pred
confident|landed|fc
landed|it|subj
surface|solid|mod
surface|soft|mod
landed|surface|on
surface|continued|rel
continued|surface|obj
continued|it|subj
continued|send|mod
send|it|subj
send|back|guest
send|pictures|obj
pictures|and|punc
pictures|data|conj
data|landing|after
continued|and|punc
continued|continue|conj
continue|it|subj
continue|do|fc
do|surface|obj
do|it|subj
do|so|mod
do|until|mod
batteries|its|gen
until|ran|comp1
ran|batteries|subj
ran|out|guest
images|initial|mod
images|black and white|nn
ran|images|obj
surface|titan|gen
images|surface|of
surface|sent|vrel
sent|surface|obj
sent|by|by-subj
sent|huygens|by
sent|before|mod
est|noon|nn
before|astonished|comp1
astonished|est|subj
astonished|scientists|obj
feat|scientific|mod
years|25|amount-value
farthest|earth|from
earth|that|c
landed|earth|obj1
landed|spacecraft|subj
landed|it|obj2
is|also|amod
landing|first|post
is|landing|pred
landing|spacecraft|of
spacecraft|moon|on
moon|planet|of
