ruled|march 1 , 2005 ,|on
ruled|supreme court|subj
ruled|5-4|obj
penalty|death|nn
penalty|murderers|for
murderers|who|whn
were|under|pred
were|age|under
age|18|num
age|time|at
crime|their|gen
time|crime|of
justice|unconstitutional|mod
is|justice|pred
justice|anthony kennedy|person
said|fin|subj
said|in|guest
said|majority|in
said|opinion|obj
opinion|that|c
struggle|still|mod-before
because|struggle|comp1
struggle|juveniles|subj
struggle|define|fc
define|juvenile|subj
identities|their|gen
define|identities|obj
supportable|less|mod
is|supportable|pred
conclude|it|subj
conclude|that|c
crime|heinous|mod
is|evidence|pred
depraved|irretrievably|mod
character|depraved|mod
evidence|character|of
noted|he|subj
noted|that|c
nation|last|post
nation|remaining|mod
was|nation|pred
nation|abolish|rel
abolish|nation|subj
penalty|death|nn
abolish|penalty|obj
penalty|minors|for
comment|his|gen
reignited|comment|subj
reignited|debate|obj
consideration|court|gen
debate|consideration|over
laws|foreign|mod
consideration|laws|of
laws|and|punc
laws|opinions|conj
opinions|interpreting|rel
interpreting|opinion|subj
interpreting|constitution|obj
