probe|huygens|nn
probe|space|nn
probe|built|vrel
built|and|punc
built|managed|conj
managed|european space agency|by
carried|probe|obj
carried|by|by-subj
spacecraft|nasa|gen
spacecraft|cassini|nn
carried|spacecraft|by
journey|7-year|nn
spacecraft|journey|on
journey|saturn|to
separated|it|subj
separated|successfully|mod
successfully|cassini|from
cassini|christmas eve|on
separated|and|punc
separated|began|conj
began|it|subj
descent|2.5-million-mile|nn
descent|20-day|nn
began|descent|obj
titan|saturn|gen
titan|largest|mod
titan|moon|nn
descent|titan|to
moon|only|mod
moon|solar system|in
solar system|that|whn
has|solar system|subj
has|atmosphere|obj
descent|its|gen
atmosphere|descent|during
sample|it|subj
sample|titan|obj
everything|atmosphere|nn
work|everything|subj
work|perfectly|mod
work|because|mod
because|is|comp1
is|way|pred
adjust|everything|subj
adjust|huygens|obj
progress|course|nn
way|was|comp1
followed|carefully|amod
was|followed|pred
followed|by|by-subj
followed|nasa|by
nasa|and|punc
nations|16|num
nations|european|nn
nasa|nations|conj
nations|involved|vrel
involved|project|in
