acquitted|march 2005|in
judge|josephson|person
acquitted|judge|subj
acquitted|ripudaman malik|obj
ripudaman malik|and|punc
ripudaman malik|ajaib bagir|conj
counts|eight|nn
ajaib bagir|counts|on
counts|murder|of
murder|and|punc
murder|conspiracy|conj
acquitted|because|mod
because|failed|comp1
failed|government|subj
failed|make|fc
make|government|subj
case|conclusive|mod
make|case|obj1
victims|plane|nn
victims|crash|nn
make|victims|desc
devastated|families|obj
devastated|and|punc
devastated|demanded|conj
demanded|families|subj
inquiry|public|mod
demanded|inquiry|obj
see|prime minister|subj
benefit|calling|to
calling|prime minister|subj
inquiry|public|mod
calling|inquiry|obj1
police|canadian|nn
calling|police|desc
see|disappointed|fc
disappointed|benefit|obj
sought|call|at
disappointed|sought|fc
sought|prosecutors|subj
sought|grounds|obj
appeal|prosecutor|subj
ruling|josephson|gen
appeal|ruling|obj
newspapers|canada|gen
grounds|shocked|comp1
shocked|newspapers|obj
shocked|acquittals|at
sikhs|two|nn
acquittals|sikhs|of
sikhs|and|punc
globe|toronto-based|mod
sikhs|globe|conj
globe|and|punc
globe|mail|conj
mail|devoted|vrel
devoted|mail|obj1
page|its|gen
page|front|mod
devoted|page|obj2
innocent|headline|nn
innocent|"|punc
page|innocent|to
innocent|"|punc
innocent|and|punc
innocent|names|conj
victims|329|num
names|victims|of
