acquitted|16 march|on
acquitted|judge|subj
sikhs|two|nn
sikhs|canadian|nn
acquitted|sikhs|obj
sikhs|charged|pnmod
saying|air india|nn
saying|bombings|nn
charged|saying|in
witnesses|prosecution|gen
witnesses|major|mod
were|not|neg
were|credible|pred
justice|british columbia|nn
justice|supreme court|nn
stated|justice|subj
stated|that|c
failed|prosecution|subj
failed|prove|fc
prove|prosecution|subj
prove|men|obj
men|guilty|pnmod
doubt|reasonable|mod
guilty|doubt|beyond
prove|but|punc
prove|added|conj
added|prosecution|subj
added|that|c
was|certain|pred
certain|originated|fc
originated|bombs|subj
originated|flights|on
flights|vancouver|out of
heard|he|subj
heard|case|obj
case|jury|without
request|defendants|gen
jury|request|at
sikhs|two|nn
request|released|comp1
released|sikhs|obj
released|immediately|mod
immediately|shocked|comp1
shocked|verdict|subj
shocked|everyone|obj
criticized|sharply|mod-before
criticized|people|subj
criticized|police|obj
police|and|punc
services|secret|nn
police|services|conj
criticized|and|punc
criticized|demanded|conj
demanded|people|subj
investigation|government|nn
demanded|investigation|obj
