hong kong disneyland|opened|vrel
opened|hong kong disneyland|obj
opened|as|mod
scheduled|12 september|on
scheduled|80%|over
80%|visitors|of
visitors|first month|in
rated|hong kong disneyland|subj
experience|their|gen
rated|experience|obj
rated|as|mod
good|very|mod
the park|good|mod
good|or|punc
good|excellent|conj
as|drew|comp1
drew|the park|subj
visitors|fewer|mod
drew|visitors|obj
months|its|gen
months|first two|amount-value
expected|months|in
offering|discount|obj
discount|hk|for
disneyland|residents|nn
refused|steadfastly|mod-before
refused|disneyland|subj
refused|disclose|fc
disclose|disneyland|subj
move|attendance|nn
move|figures-a|mod
disclose|move|obj
move|that|whn
angered|move|subj
angered|lawmakers|obj
angered|since|mod
since|owns|comp1
owns|government|subj
stake|57%|nn
owns|stake|obj
disney|park|nn
disney|in|nn
disney|late|mod
disney|november|nn
said|disney|subj
been|"|punc
been|well|punc
been|over|punc
been|"|punc
workers|one million|nn
workers|guests|nn
been|workers|pred
said|complained|fc
complained|fin|subj
hours|long|mod
complained|hours|about
turnarounds|short|mod
hours|turnarounds|conj
turnarounds|and|punc
turnarounds|lack|conj
lack|breaks|of
