sikhs|two|nn
sikhs|ripudaman malik|conj
ripudaman malik|and|punc
ripudaman malik|ajaib bagri|conj
bombing|1985|num
charged|bombing|with
jet|air india|nn
bombing|jet|of
jet|that|whn
killed|jet|subj
passengers|329|num
killed|passengers|obj
of|and|punc
of|with|conj
of|killing|with
handlers|two|nn
handlers|baggage|nn
killing|handlers|obj
arguments|narita airport final|nn
handlers|arguments|at
murder|their|gen
concluded|murder|in
concluded|trial|subj
believe|december 2004|in
concluded|believe|fc
believe|prosecutors|subj
motive|sikhs|gen
believe|was|fc
was|avenge|pred
attack|india|gen
attack|1984|num
avenge|attack|obj
attack|golden temple|on
golden temple|amritsar|in
was|not|neg
settled|trial|obj
settled|years|due to
work|bungled|mod
work|police|nn
settled|work|of
killings|unexpected|mod
work|killings|conj
killings|witnesses|of
witnesses|and|punc
witnesses|suspect|conj
suspect|and|punc
testimonies|vague|mod
vague|and|punc
vague|contradictory|conj
suspect|testimonies|conj
justice|ian josephson|person
justice|who|whn
heard|justice|subj
heard|case|obj
case|jury|without
deliver|justice|subj
decision|his|gen
deliver|decision|obj
decision|march 2005|in
