hong kong disneyland|joint venture|appo
joint venture|disney|between
disney|and|punc
government|hong kong|nn
disney|government|conj
scheduled|hong kong disneyland|obj
scheduled|open|mod
open|hong kong disneyland|subj
rehearsal|12 september|nn
open|rehearsal|on
staged|days|obj
staged|month|for
month|opening|before
opening|day|subj
opening|giving|mod
giving|"|punc
members|cast|nn
giving|members|obj1
giving|"|punc
giving|chance|obj2
chance|practice|rel
practice|chance|subj
performances|their|gen
practice|performances|obj
performances|refused|rel
refused|performances|obj
refused|disneyland|subj
refused|reduce|mod
reduce|disneyland|subj
capacity|its|gen
maximum|daily|mod
capacity|maximum|mod
reduce|capacity|obj
capacity|30,000|of
30,000|complaints|despite
visitors|early|mod
complaints|visitors|from
crowds|large|mod
visitors|crowds|about
visitors|and|punc
all|long|mod
all|lines|nn
visitors|all|conj
all|16,000|num
day|opening|mod
sold out|tickets|obj
disney|vintage|nn
is|disney|pred
is|aspects|with
culture|local|mod
aspects|culture|of
culture|including|rel
including|culture|subj
shui|feng|nn
including|shui|obj
foods|asian|mod
foods|and|punc
foods|signs|conj
protests|chinese|nn
signs|protests|in
forced|foods|subj
remove|them|subj
soup|shark|nn
soup|fin|nn
remove|soup|obj
menus|their|gen
soup|menus|from
