considers|taiwan|subj
plan|prc|gen
considers|plan|obj1
plan|enact|rel
enact|plan|subj
law|anti-secession|mod
enact|law|obj
move|provocative|mod
considers|move|obj2
move|change|rel
change|move|subj
change|status quo|obj
status quo|taiwan strait emphasizing|in
is|not|neg
is|part|pred
part|prc|of
claims|beijing|nn
prc|claims|as
believes|taiwan|subj
believes|aimed at|fc
aimed at|legislation|obj
aimed at|establishing|mod
establishing|legislation|subj
justification|legal|mod
establishing|justification|obj
invasion|beijing|gen
justification|invasion|for
invasion|island|of
u.s.|and|punc
u.s.|e.u.consider|conj
legislation|counterproductive|pnmod
counterproductive|peace|to
claims|prc|subj
claims|that|c
designed|law|obj
designed|check|mod
check|law|subj
activities|secessionist|nn
check|activities|obj
of|"|punc
forces|taiwan|nn
forces|independence|nn
forces|"|punc
activities|forces|of
check|and|punc
check|promote|conj
promote|law|subj
reunification|china|gen
promote|reunification|obj
legislature|prc|nn
scheduled|legislature|obj
scheduled|take up|mod
take up|legislature|subj
law|anti-secession|mod
take up|law|obj
law|march|in
